Added tls support
vostok/clusterclient.singular pull request #24
Opened 2022-08-09 06:38 UTC by HolyPrapor

2022-08-23 13:01 UTC, TGladysheva requested changes

2022-08-23 13:01 UTC, TGladysheva commented on Vostok.ClusterClient.Singular/InternalSingularClientProvider.cs
> +                    configuration.SetupUniversalTransport(new UniversalTransportSettings().WithSingularTlsHandshakeValidator(log));
Может быть на винде не звать WithSingularTlsHandshakeValidator? Чтобы не делать лишней работы, когда не нужно

2022-08-23 13:01 UTC, TGladysheva commented on Vostok.ClusterClient.Singular/InternalSingularClientProvider.cs
> +                    configuration.SetupUniversalTransport(new UniversalTransportSettings().WithSingularTlsHandshakeValidator(log));
А то там аж соурс в КК создается

2022-08-23 13:01 UTC, TGladysheva commented on Vostok.ClusterClient.Singular/Helpers/TransportSettingsExtensions.cs
> +        var thumbprintsProvider = new ClusterConfigThumbprintVerificationSettingsProvider(
Очень часто клиента создают per request. А тут внутри каждый раз создается  ConfigurationProvider и Source и каждый раз заново парсится. В таком случае мы используем кэш.
А ConfigurationProvider вообще IDisposable, на НТ не было замечено никакой утечки ресорсов?

2022-08-23 13:01 UTC, TGladysheva commented on Vostok.ClusterClient.Singular/Helpers/TransportSettingsExtensions.cs
> +    public static SocketsTransportSettings WithSingularTlsHandshakeValidator(this SocketsTransportSettings settings, ILog log)
А эти методы где предполагается использовать?

2022-08-23 13:01 UTC, TGladysheva commented on Vostok.ClusterClient.Singular/Helpers/TransportSettingsExtensions.cs
> +        settings.RemoteCertificateValidationCallback = GetValidator(log).Verify;
Может в этих методах ничего не делать, если запускаемся на винде, как думаешь?

2022-08-26 02:42 UTC, HolyPrapor commented on Vostok.ClusterClient.Singular/InternalSingularClientProvider.cs
> +                    configuration.SetupUniversalTransport(new UniversalTransportSettings().WithSingularTlsHandshakeValidator(log));
Тут у меня соображение такое: если OS доверяет сертификату, то лишней работы (помимо периодического обновления сурса) мы не делаем (на один if больше проверяем, не критично), так что за производительность я бы тут всё-таки не переживал.

С другой стороны, не хочется добавлять сюда логику по проверке ОС.
Может через пару лет ситуация поменяется наоборот: на Линуксе всё будет работать по-дефолту, а на винде - нет.

Тут всё-таки проблема не с особенностью ОС, а просто наш конкретный кейс, что на винде всё работает.

2022-08-26 02:45 UTC, HolyPrapor commented on Vostok.ClusterClient.Singular/Helpers/TransportSettingsExtensions.cs
> +        var thumbprintsProvider = new ClusterConfigThumbprintVerificationSettingsProvider(
Я просто не включил валидацию сертификата 🤦🏻 

НТ на виндовых агентах гонялось, вот я и не заметил.

Валидно, надо сделать кэш.

2022-08-26 02:46 UTC, HolyPrapor commented on Vostok.ClusterClient.Singular/Helpers/TransportSettingsExtensions.cs
> +    public static SocketsTransportSettings WithSingularTlsHandshakeValidator(this SocketsTransportSettings settings, ILog log)
Это просто для пользователей, не все ведь `UniversalTransport` используют, наверное

2022-08-26 02:47 UTC, HolyPrapor commented on Vostok.ClusterClient.Singular/Helpers/TransportSettingsExtensions.cs
> +        settings.RemoteCertificateValidationCallback = GetValidator(log).Verify;
Ответил в другом похожем комментарии

2022-08-29 12:39 UTC, TGladysheva commented on Vostok.ClusterClient.Singular/InternalSingularClientProvider.cs
> +                    configuration.SetupUniversalTransport(new UniversalTransportSettings().WithSingularTlsHandshakeValidator(log));
> К слову, кажется, в InternalSingularClientProvider можно было и не добавлять проверку TLS? Он же просто за настройками ходит

Согласна

2022-08-29 12:43 UTC, TGladysheva commented on Vostok.ClusterClient.Singular/InternalSingularClientProvider.cs
> +                    configuration.SetupUniversalTransport(new UniversalTransportSettings().WithSingularTlsHandshakeValidator(log));
Остальное тоже ок, давай оставим как есть

2022-09-05 12:47 UTC, merged